"""Telegram delivery adapter for NEXUS-ASTRA trade signals."""

from __future__ import annotations

import json
import logging
import os
from typing import Any, Mapping

from telegram import Bot
from telegram.constants import ParseMode
from telegram.helpers import escape_markdown

logger = logging.getLogger(__name__)

TELEGRAM_BOT_TOKEN_ENV = "TELEGRAM_BOT_TOKEN"
TELEGRAM_CHAT_ID_ENV = "TELEGRAM_CHAT_ID"

ALLOWED_TELEGRAM_STATUSES = {"APPROVED", "WATCHLIST", "RISK_OFF", "DATA_FAIL"}


async def send_telegram_signal(payload: Mapping[str, Any] | str) -> dict[str, Any]:
    """Send a structured signal payload to Telegram as a formatted markdown message.

    Dispatches ONLY when status is in [APPROVED, WATCHLIST, RISK_OFF, DATA_FAIL].
    Never dispatches on NO_TRADE.
    """
    signal = _normalize_payload(payload)
    status = str(signal.get("status") or signal.get("Status") or "APPROVED").upper()

    # Rule: Never send on NO_TRADE
    if status == "NO_TRADE":
        logger.info("Telegram dispatch suppressed: status is NO_TRADE.")
        return {
            "status": "suppressed",
            "reason": "NO_TRADE signals are never dispatched to Telegram",
        }

    # Rule: Only send when status in [APPROVED, WATCHLIST, RISK_OFF, DATA_FAIL]
    if status not in ALLOWED_TELEGRAM_STATUSES:
        logger.info(
            f"Telegram dispatch suppressed: status '{status}' not in {sorted(ALLOWED_TELEGRAM_STATUSES)}"
        )
        return {
            "status": "suppressed",
            "reason": f"Status '{status}' is not eligible for Telegram dispatch",
        }

    bot_token = os.getenv(TELEGRAM_BOT_TOKEN_ENV)
    chat_id = os.getenv(TELEGRAM_CHAT_ID_ENV)

    if not bot_token:
        raise ValueError(f"Missing required environment variable: {TELEGRAM_BOT_TOKEN_ENV}")
    if not chat_id:
        raise ValueError(f"Missing required environment variable: {TELEGRAM_CHAT_ID_ENV}")

    message_text = _format_markdown_message(signal)
    bot = Bot(token=bot_token)
    sent_message = await bot.send_message(
        chat_id=chat_id,
        text=message_text,
        parse_mode=ParseMode.MARKDOWN_V2,
        disable_web_page_preview=True,
    )

    return {
        "status": "sent",
        "chat_id": chat_id,
        "message_id": sent_message.message_id,
        "symbol": signal.get("Symbol"),
        "signal_type": signal.get("Signal Type"),
    }


def _normalize_payload(payload: Mapping[str, Any] | str) -> dict[str, Any]:
    if isinstance(payload, str):
        try:
            decoded = json.loads(payload)
        except json.JSONDecodeError as exc:
            raise ValueError("Payload string must contain valid JSON.") from exc
    else:
        decoded = dict(payload)

    status = str(decoded.get("status") or decoded.get("Status") or "APPROVED").upper()
    if status == "NO_TRADE":
        return decoded

    if "Symbol" in decoded:
        required_keys = [
            "Symbol",
            "Signal Type",
            "Entry Price",
            "Target",
            "Stop Loss",
            "Confidence Score",
            "Position Size",
        ]
        missing_keys = [key for key in required_keys if key not in decoded]
        if missing_keys:
            raise ValueError(f"Missing required payload fields: {', '.join(missing_keys)}")

    return decoded


def _format_markdown_message(signal: Mapping[str, Any]) -> str:
    symbol = _escape(signal["Symbol"])
    signal_type = _escape(signal["Signal Type"])
    entry_price = _format_numeric(signal["Entry Price"])
    target = _format_numeric(signal["Target"])
    stop_loss = _format_numeric(signal["Stop Loss"])
    confidence_score = _format_numeric(signal["Confidence Score"])
    position_size = _format_numeric(signal["Position Size"])

    msg = (
        f"*NEXUS\-ASTRA Signal Alert*\n"
        f"━━━━━━━━━━━━━━━━━━━━\n"
        f"*Symbol:* `{symbol}`\n"
        f"*Signal Type:* `{signal_type}`\n"
        f"*Entry Price:* `{entry_price}`\n"
        f"*Target:* `{target}`\n"
        f"*Stop Loss:* `{stop_loss}`\n"
        f"*Confidence Score:* `{confidence_score}`\n"
        f"*Position Size:* `{position_size}`\n"
    )

    # Append optional options/gamma metrics if present
    if "PCR" in signal:
        msg += f"*NIFTY PCR:* `{_format_numeric(signal['PCR'])}`\n"
    if "Max Pain" in signal:
        msg += f"*NIFTY Max Pain:* `{_format_numeric(signal['Max Pain'])}`\n"
    if "Zero Gamma" in signal:
        msg += f"*NIFTY Zero Gamma:* `{_format_numeric(signal['Zero Gamma'])}`\n"
    if "Pin Risk Score" in signal:
        msg += f"*NIFTY Pin Risk:* `{_format_numeric(signal['Pin Risk Score'])}`\n"

    msg += (
        f"━━━━━━━━━━━━━━━━━━━━\n"
        f"_Delivery generated by NEXUS\-ASTRA v3\.0_"
    )
    return msg



def _format_numeric(value: Any) -> str:
    if isinstance(value, (int, float)):
        return f"{float(value):.2f}"
    return _escape(str(value))


def _escape(value: Any) -> str:
    return escape_markdown(str(value), version=2)
